# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7baac88810f12348072ab8d7f7a77d1a0366636fbcadb9988c0b462e9f722904fb0643ce95ea68b73be9e51e27a5a622ad486fa450bcfe35874005d10f86ff1b

test:
  secret_key_base: 236a133a028b0870ee1a32e57058305b55d5fd7324fc88b4a798f2d635a7cfebb40899ceb8d64092c95b9e29f02cd42cd3e56b70a9eff418efb2d0678543b0e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
